### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by pcg92** [0ximDigital/Rx2Animations#1]
Im using Rxjava2 but including Rxjava1 to use this library.
Do you need help?

**Comment by 0ximDigital** [comment]
Hi pcegarra,
thank you for using this library 💪

I have some good news for you, the Rx2 version will be published this week!

It would be awesome if you could test it when it comes out :)

**Comment by pcg92** [comment]
Good news! Im going to be the first trying this version, Thanks!

**Comment by 0ximDigital** [comment]
Closing this issue with the release of Rx2Animations v0.9.0.  🚀
